import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Test Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
      </Head>
      <main>
        <div className="relative">
          <div className="mx-32">
            <Image src="/images/bgSec04.jpg" width="2000" height="10" className="mx-auto mt-20 animate-fade-in-bottom" alt="" />
          </div>
          <p className="absolute top-28 right-16 text-7xl font-sans animate-fade-in-right">My <br />Works</p>
        </div>
        <div className="flex mt-36">
          <Image src="/images/imgProject.jpg" width="400" height="10" className="flex-auto" alt="" />
          <Link href="/portfolio" className="flex-auto">
            ポートフォリオ集
          </Link>
        </div>
      </main>
    </>
  )
}
