import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Test Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
      </Head>
      <main>
        <div id="wrapper">

          <div id="sidebar">
            <div id="sidebarWrap">
              <h1><Image src="/images/logo.png" width="87" height="25" alt="logo" /></h1>
              <nav id="mainnav">
                <p id="menuWrap"><a id="menu"><span id="menuBtn"></span></a></p>
                <div className="panel">
                  <ul>
                    <li><a href="#top">TOP</a></li>
                    <li><a href="#sec01">MESSAGE</a></li>
                    <li><a href="#sec02">GALLERY</a></li>
                    <li><a href="#sec03">BRAND</a></li>
                    <li><a href="#sec04">PROJECT</a></li>
                    <li><a href="#sec05">COMPANY</a></li>
                  </ul>
                  <ul id="sns">
                    <li><a href="#" target="_blank"><Image src="/images/iconFb.png" width="20" height="20" alt="FB" /></a></li>
                    <li><a href="#" target="_blank"><Image src="/images/iconTw.png" width="20" height="20" alt="twitter" /></a></li>
                    <li><a href="#" target="_blank"><Image src="/images/iconInsta.png" width="20" height="20" alt="Instagram" /></a></li>
                    <li><a href="#" target="_blank"><Image src="/images/iconYouTube.png" width="20" height="20" alt="You Tube" /></a></li>
                  </ul>
                </div>
              </nav>
            </div>
          </div>

          <div id="content">
            <p id="mainImage"><Image src="/images/mainImg.jpg" alt="" width="20" height="20" /></p>
            <section id="sec01">
              <header>
                <h2><span>MESSAGE</span></h2>
              </header>
              <div className="innerS">
                ホームページサンプル株式会社では最新技術と自然との調和を目指します。革新的な技術で世の中を動かす企業を目指します。ホームページサンプル株式会社。ホームページサンプル株式会社では最新技術と自然との調和を目な技術で世の中を動かす企業を目指します。ホームページサンプル株式会社では最新技術と自然との調和を目指します。革新的な技術で世の中を動かす企業を目指します。
              </div>
            </section>
            <section id="sec02">
              <header>
                <h2><span>GALLERY</span></h2>
              </header>
              <ul id="gallery">
                <li><Image src="/images/photo01.jpg" width="360" height="350" alt="" /></li>
                <li><Image src="/images/photo02.jpg" width="360" height="350" alt="" /></li>
                <li><Image src="/images/photo03.jpg" width="360" height="350" alt="" /></li>
                <li><Image src="/images/photo04.jpg" width="360" height="350" alt="" /></li>
                <li><Image src="/images/photo05.jpg" width="360" height="350" alt="" /></li>
                <li><Image src="/images/photo06.jpg" width="360" height="350" alt="" /></li>
                <li className="full"><Image src="/images/photo07.jpg" width="1080" height="695" alt="" /></li>
                <li><Image src="/images/photo08.jpg" width="360" height="350" alt="" /></li>
                <li><Image src="/images/photo09.jpg" width="360" height="350" alt="" /></li>
                <li><Image src="/images/photo10.jpg" width="360" height="350" alt="" /></li>
                <li><Image src="/images/photo11.jpg" width="360" height="350" alt="" /></li>
                <li><Image src="/images/photo12.jpg" width="360" height="350" alt="" /></li>
                <li><Image src="/images/photo13.jpg" width="360" height="350" alt="" /></li>
              </ul>
            </section>
            <section id="sec03">
              <header>
                <h2><span>BRAND</span></h2>
              </header>
              <div className="inner">
                <ul className="col4">
                  <li>
                    <p className="Image"><Image src="/images/logo01.png" width="168" height="168" alt="" /></p>
                    <p>ホームページサンプル株式会社では最動かす企業を目指します。</p>
                  </li>
                  <li>
                    <p className="Image"><Image src="/images/logo02.png" width="168" height="168" alt="" /></p>
                    <p>革新的な技術で世の中を動かす企業を目します。世の中を動かす。</p>
                  </li>
                  <li>
                    <p className="Image"><Image src="/images/logo03.png" width="168" height="168" alt="" /></p>
                    <p>株式会社では最動かす企業を目指しますージン企業を目指します。</p>
                  </li>
                  <li>
                    <p className="Image"><Image src="/images/logo04.png" width="168" height="168" alt="" /></p>
                    <p>株式会社では最動かす企業を指しますージサン企業を目指します。</p>
                  </li>
                </ul>
              </div>
            </section>
            <section id="sec04">
              <header>
                <h2><span>PROJECT</span></h2>
              </header>
              <div className="inner">
                <div className="article">
                  <Image src="/images/photo14.jpg" width="370" height="224" alt="" />
                  <p>ホームページサンプル株式会社では最新技術と自然との調和を目指します。革新的な革新的な革新的な技術で世の中を技術で世の中を技術で世の中を動かす企業を目指します。</p>
                  <p>ホームページサンプル株式会社。ホームページサンプル最新技術と自然との調和を目指します。革新的な技術で世の中を動かす企業を目指します。ホームページサンプル株式会社。ホームページサンプル最新技術と自然との調和を目指し調和を目指し調和を目指します。革新的な技術で世の中を動かす企業を目指します。</p>
                </div>
                <div className="article">
                  <Image src="/images/photo15.jpg" width="370" height="224" alt="" />
                  <p>ホームページサンプル株式会社では最新技術と自然との調和を目指します。革新的な革新的な革新的な技術で世の中を技術で世の中を技術で世の中を動かす企業を目指します。</p>
                  <p>ホームページサンプル株式会社。ホームページサンプル最新技術と自然との調和を目指します。革新的な技術で世の中を動かす企業を目指します。ホームページサンプル株式会社。ホームページサンプル最新技術と自然との調和を目指し調和を目指し調和を目指します。革新的な技術で世の中を動かす企業を目指します。</p>
                </div>
              </div>
            </section>
            <section id="sec05">
              <header>
                <h2><span>COMPANY</span></h2>
              </header>
              <div className="inner">
                <ul className="col2">
                  <li>
                    <p>〒103-1234<br />見本県見本市仮区見本町1-3-5</p>
                    <p>TEL 01234-567-8901</p>
                    <p>e-Mail info@example.com</p>
                    <p>営業時間 10:00〜20:00（水曜定休）</p>
                    <p>※都合により休業する場合がございます</p>
                  </li>
                  <li>
                    <div id="map">
                      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3198.5937927089367!2d136.92980931491988!3d36.70829797996758!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x5ff781ec5af4ca3f%3A0x2ade3e8e4c2801b8!2z56aP5bKh6aeF!5e0!3m2!1sja!2sus!4v1478313402186"></iframe>
                    </div>
                  </li>
                </ul>
              </div>
            </section>

            <footer id="footer">
              Copyright(c) 2016 Sample Inc. All Rights Reserved. Design by <a href="http://f-tpl.com" target="_blank">http://f-tpl.com</a>
            </footer>

          </div>
        </div>
      </main>
    </>
  )
}
